### ISSUE TITLE
这中文翻译看起来太吃力了

### ISSUE THREAD

**Issue by sunq0001** [duguying/parsing-techniques#26]
- 章节 [如: 1.3]
- 原文页码 [如: 29]
这中文翻译看起来太吃力了，还不如直接看英文。 
不能直接按照英语语法结构直译的。

**Comment by duguying** [comment]
有更好的翻译欢迎发PR

**Comment by wizardforcel** [comment]
> * 章节 [如: 1.3]
> * 原文页码 [如: 29]
>   这中文翻译看起来太吃力了，还不如直接看英文。
>   不能直接按照英语语法结构直译的。

这样便于校对和做平行语料，没啥不好。
